language: node_js

node_js:
  - "12"

install:
    - yarn 

script:
    - yarn run build

deploy: 
    provider: heroku
    api_key:
      secure: "UvBpsmhMwkvCXIFCkrlDo352+u8MoZzvPe5NdghHAyTpDequRx0wh8AY8vCO+PpQg9o54yMQfQ+xam4LdwHF7xcPuEyx68tPrup+kgb4myh38RTes5XdsAn/xlUaJAdUv1hGdUNabd/IrGioO7BwXCGtWj4riiy2V7RxSOQ2wD54qb0iwfFvY7Rwq+gmD6zJ+MogBhBLDd23i7ZfVEcWK3izPEZm1SNBeE1Yaq3/lDo0aFDRb6eVTxsV7fSMpsIN68XctdS5h8ejRPKESP5/E1FYb5EusFC49ftgD49d/i3rG0/H+Lx5iMAmtSa7V0sBaQWCa9WIbnlG8LmN1Lbcqff74dCrDTOZ9VGEuq6Qtmhcf4oqAIYbMZC6IkGZEl+UEfejeB7QcuZcRfdZKsoUCuFDq17WtE2jIkZAdCa4JQkqqMYupnjgktOW4MZMWqRA3llOBXTalLbt9Xa+9tAEy0Ma9JuwP3oQZxl4D7y6aSbthH1DCutK6rYZkSN3409rf1UtEvaCJuLj+IKX8bZQxJi1xjWIY4SJDyN80Stel+oZS8j2jJAy7Noz9wLQ6o/clDJmn1fyilLXsvTt/Cutxd8TIeBBkBpGwiLuuqYSvnxem2WG2uFMN1SA4tnupwYPNLTgx1H3vHpNCPlEW7AL0LXpWpwn5mXRmg8NZu0YZkU="
